version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rider_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rider_claims
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: rider_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: rider_backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/rider_claims?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: rider_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata: