import { AttachmentCategory, DemoDatabase } from './types';

const defaultAttachments: AttachmentCategory[] = [
  {
    key: 'identity_third',
    title: '身份证明（三者）',
    files: [
      { id: 'id-1', name: '身份证正面.jpg', type: 'image' },
      { id: 'id-2', name: '身份证反面.jpg', type: 'image' },
    ],
  },
  {
    key: 'identity_rider',
    title: '身份证明（骑手）',
    files: [],
  },
  {
    key: 'medical_invoice_third',
    title: '医疗费发票（三者）',
    files: [
      { id: 'med-1', name: '门诊发票.pdf', type: 'pdf' },
    ],
  },
  {
    key: 'medical_invoice_rider',
    title: '医疗费发票（骑手）',
    files: [],
  },
  {
    key: 'medical_itemized_third',
    title: '医疗费用清单（三者）',
    files: [],
  },
  {
    key: 'medical_itemized_rider',
    title: '医疗费用清单（骑手）',
    files: [],
  },
  {
    key: 'appraisal_report_third',
    title: '鉴定报告（三者）',
    files: [
      { id: 'app-1', name: '伤残鉴定报告.pdf', type: 'pdf' },
    ],
  },
  {
    key: 'appraisal_report_rider',
    title: '鉴定报告（骑手）',
    files: [],
  },
  {
    key: 'medical_record_third',
    title: '医疗记录（三者）',
    files: [
      { id: 'med-2', name: '诊断证明.jpg', type: 'image' },
    ],
  },
  {
    key: 'medical_record_rider',
    title: '医疗记录（骑手）',
    files: [],
  },
  {
    key: 'accident',
    title: '事故证明',
    files: [
      { id: 'acc-1', name: '事故现场照片_1.jpg', type: 'image' },
      { id: 'acc-2', name: '事故现场照片_2.jpg', type: 'image' },
    ],
  },
  {
    key: 'payment',
    title: '支付信息',
    files: [],
  },
  {
    key: 'repair',
    title: '维修单据',
    files: [],
  },
  {
    key: 'work',
    title: '工作证明',
    files: [],
  },
  {
    key: 'vehicle',
    title: '车辆文件',
    files: [],
  },
  {
    key: 'other',
    title: '其他单证',
    files: [],
  },
];

export const seedData: DemoDatabase = {
  cases: [
    {
      id: 'case-001',
      case_no: 'CL202604070001',
      vehicle_type: 'E_BIKE',
      vehicle_label: '电动自行车（非机动车）',
      is_motor: false,
      status: 'AGREEMENT_APPROVED',
      reporter: '李小明',
      rider_name: '王强',
      rider_type: '专送',
      company: '美团外卖',
      report_time: '2026-04-05 11:02',
      accident_time: '2026-04-05 10:30',
      accident_location: '上海市浦东新区张江路',
      product: '雇主责任险',
      has_litigation: false,
      has_investigation: false,
      investigation_blocking: false,
      liability_ratio: 100,
      tasks: [
        {
          id: 'task-001-1',
          task_type: 'rider_injury',
          status: 'AGREEMENT_APPROVED',
          loss_items: [
            { id: 'li-1', category: 'MEDICAL_FEE', amount: 3800, remark: '住院12天费用', audited: true },
            { id: 'li-2', category: 'NURSING_FEE', amount: 600, remark: '护工3天', audited: true },
          ],
        },
        {
          id: 'task-001-2',
          task_type: 'third_property',
          status: 'AGREEMENT_APPROVED',
          loss_items: [
            { id: 'li-3', category: 'VEHICLE_REPAIR', amount: 1200, remark: '对方电瓶车维修', audited: true },
          ],
        },
      ],
      task_details: {},
      attachments: defaultAttachments,
      payment_infos: [],
      audit_logs: [{ id: 'log-1', time: '2026-04-07 16:50', operator: '管理员-王五', action: '创建报案' }],
    },
    {
      id: 'case-004',
      case_no: 'CL202604070004',
      vehicle_type: 'E_BIKE',
      vehicle_label: '电动自行车（非机动车）',
      is_motor: false,
      status: 'PENDING',
      reporter: '孙芳',
      rider_name: '陈明',
      rider_type: '众包',
      company: '饥了么',
      report_time: '2026-04-07 17:10',
      accident_time: '2026-04-07 16:45',
      accident_location: '深圳市南山区科技园',
      product: '雇主责任险',
      has_litigation: false,
      has_investigation: false,
      investigation_blocking: false,
      liability_ratio: 100,
      tasks: [
        { id: 'task-004-1', task_type: 'rider_injury', status: 'PENDING', loss_items: [] },
        { id: 'task-004-2', task_type: 'third_injury', status: 'PENDING', loss_items: [] },
        { id: 'task-004-3', task_type: 'third_property', status: 'PENDING', loss_items: [] },
      ],
      task_details: {},
      attachments: defaultAttachments,
      payment_infos: [],
      audit_logs: [{ id: 'log-2', time: '2026-04-07 17:10', operator: '客服专员', action: '创建报案' }],
    },
    {
      id: 'case-005',
      case_no: 'CL202604070005',
      vehicle_type: 'E_MOTOR',
      vehicle_label: '电动摩托车（机动车）',
      is_motor: true,
      status: 'SUBMITTED_REG',
      reporter: '蒋莉',
      rider_name: '吴涛',
      rider_type: '专送',
      company: '美团外卖',
      report_time: '2026-04-07 08:55',
      accident_time: '2026-04-07 08:20',
      accident_location: '杭州市西湖区文三路',
      product: '团体意外险（含附加三者）',
      has_litigation: false,
      has_investigation: false,
      investigation_blocking: false,
      liability_ratio: 70,
      tasks: [
        {
          id: 'task-005-1', task_type: 'rider_injury', status: 'SUBMITTED_REG',
          loss_items: [
            { id: 'li-s1', category: 'MEDICAL_FEE', amount: 5200, remark: '骨折手术', audited: false },
            { id: 'li-s2', category: 'NURSING_FEE', amount: 900, remark: '护工5天', audited: false },
          ],
        },
        {
          id: 'task-005-2', task_type: 'third_property', status: 'SUBMITTED_REG',
          loss_items: [
            { id: 'li-s3', category: 'VEHICLE_REPAIR', amount: 8000, remark: '对方私家车维修', audited: false },
          ],
        },
      ],
      task_details: {},
      attachments: defaultAttachments,
      audit_logs: [{ id: 'log-3', time: '2026-04-07 09:00', operator: '人伤查勘员', action: '提交立案申请' }],
    },
    {
      id: 'case-006',
      case_no: 'CL202604070006',
      vehicle_type: 'FUEL_MOTOR',
      vehicle_label: '燃油摩托车（机动车）',
      is_motor: true,
      status: 'REG_APPROVED',
      reporter: '黄宇',
      rider_name: '宋平',
      rider_type: '众包',
      company: '饥了么',
      report_time: '2026-04-06 19:40',
      accident_time: '2026-04-06 19:10',
      accident_location: '成都市武侯区红牌楼',
      product: '摩托车综合险',
      has_litigation: false,
      has_investigation: false,
      investigation_blocking: false,
      liability_ratio: 50,
      tasks: [
        {
          id: 'task-006-1', task_type: 'rider_injury', status: 'REG_APPROVED',
          loss_items: [
            { id: 'li-r1', category: 'MEDICAL_FEE', amount: 11000, remark: '腰椎骨折住院', audited: false },
            { id: 'li-r2', category: 'LOST_INCOME', amount: 4500, remark: '误工30天', audited: false },
          ],
        },
        {
          id: 'task-006-2', task_type: 'third_injury', status: 'REG_APPROVED',
          loss_items: [
            { id: 'li-r4', category: 'MEDICAL_FEE', amount: 2300, remark: '三者轻伤门诊', audited: false },
          ],
        },
      ],
      task_details: {},
      attachments: defaultAttachments,
      audit_logs: [{ id: 'log-4', time: '2026-04-06 21:00', operator: '人伤审核员', action: '立案审核通过' }],
    },
    {
      id: 'case-007',
      case_no: 'CL202604070007',
      vehicle_type: 'E_BIKE',
      vehicle_label: '电动自行车（非机动车）',
      is_motor: false,
      status: 'SUBMITTED_AGREEMENT',
      reporter: '谢宁',
      rider_name: '郭晨',
      rider_type: '专送',
      company: '顺丰同城',
      report_time: '2026-04-07 13:20',
      accident_time: '2026-04-07 12:40',
      accident_location: '南京市鼓楼区中山北路',
      product: '骑手意外与三者责任险',
      has_litigation: false,
      has_investigation: false,
      investigation_blocking: false,
      liability_ratio: 80,
      tasks: [
        {
          id: 'task-007-1', task_type: 'rider_injury', status: 'SUBMITTED_AGREEMENT',
          loss_items: [
            { id: 'li-a1', category: 'MEDICAL_FEE', amount: 6800, remark: '门诊+住院', audited: false },
            { id: 'li-a2', category: 'LOST_INCOME', amount: 3200, remark: '误工20天', audited: false },
          ],
        },
        {
          id: 'task-007-2', task_type: 'third_property', status: 'SUBMITTED_AGREEMENT',
          loss_items: [
            { id: 'li-a3', category: 'VEHICLE_REPAIR', amount: 5600, remark: '对方车辆维修', audited: false },
          ],
        },
      ],
      task_details: {},
      attachments: defaultAttachments,
      audit_logs: [{ id: 'log-5', time: '2026-04-07 14:00', operator: '人伤查勘员', action: '提交协议上报' }],
    },
  ],
};